// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"review-job/internal/biz"
	"review-job/internal/conf"
	"review-job/internal/data"
	"review-job/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, elasticsearch *conf.Elasticsearch, kafka *conf.Kafka, logger log.Logger) (*kratos.App, func(), error) {
	esClient, err := data.NewESClient(elasticsearch)
	if err != nil {
		return nil, nil, err
	}
	reader := data.NewKafkaReader(kafka)
	dataData, cleanup, err := data.NewData(confData, logger, esClient, reader)
	if err != nil {
		return nil, nil, err
	}
	reviewRepo := data.NewReviewRepo(dataData, logger)
	reviewUsecase := biz.NewReviewUsecase(reviewRepo, logger)
	jobServer := server.NewJobServer(reviewUsecase)
	app := newApp(logger, jobServer)
	return app, func() {
		cleanup()
	}, nil
}
